services:
  api:
    build:
      context: .
      target: dev
    container_name: perpetuo-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    # Aqui geramos o prisma client ANTES de subir o app
    command: sh -c "npx prisma generate && npm run start:dev"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: perpetuo-postgres
    environment:
      POSTGRES_USER: perpetuo
      POSTGRES_PASSWORD: perpetuo
      POSTGRES_DB: perpetuo_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: perpetuo-redis
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: perpetuo-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: perpetuo-logstash
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "8080:8080"
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: perpetuo-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  postgres_data:
  elastic_data: